### ISSUE TITLE
Add page with Visual Studio Code Gifs

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix.dev#103]
Add page that demonstrates each VSCode feature.

**Comment by magnus-madsen** [comment]
Here is an example (I could have done a lot better):

![Derive](https://github.com/flix/flix.dev/assets/2287953/02676564-c14d-4d11-9fc6-76ab78b879e3)

**Comment by magnus-madsen** [comment]
Also I would want much better quality. Maybe GIF is not the right format?

**Comment by sockmaster27** [comment]
Like this?

https://github.com/flix/flix.dev/assets/61235930/72b270e6-1cef-410f-bba2-163f4c1231f7

I'm thinking we can just use videos, have them loop and hide their controls.

**Comment by magnus-madsen** [comment]
> Like this?

Yes. But, I think we should try to show complete functions (not just fragments).

I would like a double column layout where there is a video and some accompanying text. A bit like on the front page.

> I'm thinking we can just use videos, have them loop and hide their controls.

In what format and what is the file size?

**Comment by sockmaster27** [comment]
This one is an mp4 around 1.6MB. I could look into compressing it more if we want that.
Alternatively, we could downscale it, but doing too much, I would be worried about how it would appear on something like a 4K monitor or even just a phone screen.

**Comment by sockmaster27** [comment]
> Yes. But, I think we should try to show complete functions (not just fragments).

Is this better? Or is it still too abstract?

https://github.com/flix/flix.dev/assets/61235930/0c516848-cda4-4c2d-9c5c-8fe850356764

**Comment by magnus-madsen** [comment]
I think it would actually be best to use real code. How about you just load in `List.flix` and use some functions from that?

As for the side, I was hoping to have say 20 small videos on one page, so 1.6MB seems excessive. Maybe there is a better format?

**Comment by sockmaster27** [comment]
> I think it would actually be best to use real code. How about you just load in `List.flix` and use some functions from that?

I'm just worried that it'll get too noisy to notice subtle changes, plus it can be hard to find cases where, for example, something that was a function becomes variable without everything breaking.

**Comment by magnus-madsen** [comment]
> 

I think it will be fine, like renaming a local variable, hovering over an expression, etc.

**Comment by sockmaster27** [comment]
Like this? 🤔

https://github.com/flix/flix.dev/assets/61235930/e06ddc2f-3da6-496c-bda9-c517d55392eb

**Comment by sockmaster27** [comment]
Here's a version that only weighs 190KB

https://github.com/flix/flix.dev/assets/61235930/f9709f61-db62-434d-8814-a5eabde3090f

Not as pretty, but probably good enough, considering the size it's going to have.

**Comment by magnus-madsen** [comment]
Yes, great!

**Comment by magnus-madsen** [comment]
If you warm up the compiler a bit, it should be faster.

**Comment by magnus-madsen** [comment]
Maybe you can make page starting with just 3 such videos?

**Comment by magnus-madsen** [comment]
I guess we should decide on a specific resolution aswell. (so we use the same for each video.)

**Comment by magnus-madsen** [comment]
- [ ] Come up with a list of videos we want.

**Comment by magnus-madsen** [comment]
Fixed in master.
