### ISSUE TITLE
Problems when trying out the language

### ISSUE THREAD

**Issue by TheodorRene** [flix/flix.dev#35]
Like many others, I prefer to use an editor of my choosing and run the program in the terminal. It was pretty hard to get to this simple info.

Suggestion:

As a final subheader, add "Run manually" to https://flix.dev/get-started/ 
1. Download the compiler from the latest releases (https://github.com/flix/flix/releases/latest)
2. Run:
```
$ java -jar path/to/flix.jar init
```
This will create a project structure with src/Main.flix as the entry point
3.
```
$ java -jar path/to/flix.jar run
```

Or add a link to https://doc.flix.dev/build-and-packages/

**Comment by magnus-madsen** [comment]
We will add something like this!

**Comment by magnus-madsen** [comment]
Like this:

![image](https://user-images.githubusercontent.com/2287953/146169900-3f5f061d-7f8b-433b-8584-72fe11dc095c.png)

Any comments?

**Comment by magnus-madsen** [comment]
![image](https://user-images.githubusercontent.com/2287953/146171049-1d0474f9-f4f9-4617-89de-7e15b728a489.png)

**Comment by TheodorRene** [comment]
Looks good!

**Comment by magnus-madsen** [comment]
That is strange. Is there no `src/Main`?

**Comment by magnus-madsen** [comment]
In the second case you started Flix, but you did not specify any input files.

**Comment by magnus-madsen** [comment]
Most likely the interactive mode will disappear or be refactored.

**Comment by TheodorRene** [comment]
Okay, won't delve too much into this then 👍

**Comment by magnus-madsen** [comment]
Fixed in master.
