### ISSUE TITLE
Update samples

### ISSUE THREAD

**Issue by ninaandrup** [flix/flix.dev#53]
[Samples](https://github.com/ninaandrup/flix.dev/blob/master/src/data/Samples.js) that need to be updated:

- [ ] Polymorphic Record Update
- [ ] Polymorphic Record Extension and Restriction
- [ ] Opaque Types
- [ ] Type Aliases
- [ ] Select with Defaults and Timers
- [ ] Polymorphic First-Class Constraints
- [ ] An Interpreter for a Trivial Expression Language
- [ ] A Simple Card Game Simlulation (simulation spelled wrong???)
- [ ] Deriving Type Classes

**Comment by magnus-madsen** [comment]
Note that these come from the flix/flix repo in the folder `examples` and should be copy-pasted from there.
