### ISSUE TITLE
Update `Home` page

### ISSUE THREAD

**Issue by ninaandrup** [flix/flix.dev#54]
Examples that are not working:

- [ ] First-class Datalog Constraints
- [ ] Datalog Enriched with Lattice Semantics

**Comment by ninaandrup** [comment]
I'm not sure, why the `Datalog Enriched with Lattice Semantics` example gives me this error
```
>> Parse Error: Invalid input ';', expected "choose*", "choose", "chan", LegalLetter, ':', "->", ArgumentList, '[', '.', ::, :::, Op, '`', <+>, **, * or / (line 48, column 26):
let r = query p select (c; d) from ReadyDate(c; d);
                         ^
```

**Comment by ninaandrup** [comment]
@magnus-madsen the example with `Eq` and `Foldable` explained on the home page are not the same as declared in Flix. Are these example just to make it simple?

**Comment by magnus-madsen** [comment]
> I'm not sure, why the `Datalog Enriched with Lattice Semantics` example gives me this error
> 
> ```
> >> Parse Error: Invalid input ';', expected "choose*", "choose", "chan", LegalLetter, ':', "->", ArgumentList, '[', '.', ::, :::, Op, '`', <+>, **, * or / (line 48, column 26):
> let r = query p select (c; d) from ReadyDate(c; d);
>                          ^
> ```

@JonathanStarup Can you help here?
