### ISSUE TITLE
Update `About` page

### ISSUE THREAD

**Issue by ninaandrup** [flix/flix.dev#56]
Some of the example are not working

- [x] Basic Functional Programming (both examples)
- [x] Concurrency (1st example)`
- [x] Polymorphic Effects: Separating Pure and Impure Code
- [x] First-class Datalog Constraints (both examples)

**Comment by ninaandrup** [comment]
@magnus-madsen I'm a bit confussed. It looks like, some of the text from the https://flix.dev/about/ is missing in the code. I cannot seem to find the code for
```
def unfoldWithIter(next: () ~> Option[a]): List[a] & Impure = ...
```
It should have been [above this line somewhere](https://github.com/flix/flix.dev/blob/6a9e4e9c5de09cdb47abdb27af40c45014536369/src/page/About.js#L229).

**Comment by magnus-madsen** [comment]
I refreshed the website recently. Could that be why?

**Comment by ninaandrup** [comment]
> I refreshed the website recently. Could that be why?

Yes, now the website is up-to-date with the code :-)
