### ISSUE TITLE
New examples missing

### ISSUE THREAD

**Issue by ninaandrup** [flix/flix.dev#63]
Some of the new examples are not on the website yet.

All current examples:

- [x] `algebraic-data-types-and-pattern-matching.flix`
- [x] `an-interpreter-for-a-trivial-expression-language.flix`
- [x] `compiler-puzzle.flix`
- [x] `deriving-type-classes.flix`
- [x] `effect-polymorphic-functions.flix`
- [x] `enums-and-parametric-polymorphism.flix`
- [ ] (pending) `file-information.flix`
- [x] `first-class-constraints-and-fixpoints.flix`
- [x] `function-composition-pipelines-and-currying.flix`
- [x] `higher-order-functions.flix`
- [ ] `internal-mutability-with-regions.flix`
- [x] `lists-and-list-processing.flix`
- [x] `mutual-recursion-with-full-tail-call-elimination.flix`
- [x] `opaque-types.flix`
- [x] `pipelines-of-fixpoint-computations.flix`
- [x] `polymorphic-first-class-constraints.flix`
- [x] `polymorphic-record-extension-and-restriction.flix`
- [x] `polymorphic-record-update.flix`
- [ ] `print-a-colorful-message.flix`
- [x] `pure-and-impure-functions.flix`
- [x] `record-construction-and-use.flix`
- [x] `select-with-defaults-and-timers.flix`
- [x] `sending-and-receiving-on-channels.flix`
- [x] `simple-card-game.flix`
- [ ] (do not add) `the-ast-typing-problem-with-polymorphic-records.flix`
- [x] `type-aliases.flix`
- [x] `using-channels-and-select.flix`
- [ ] (do not add) `using-get-opt.flix`
- [ ] `using-laziness-for-infinite-streams.flix`
- [ ] `using-laziness-for-logging.flix`
- [ ] `using-laziness-to-compute-fibonacci.flix`
- [ ] (pending) `working-with-files-and-directories.flix`

**Comment by ninaandrup** [comment]
@magnus-madsen I'm not sure, if this is what you wanted. But here is a list of all example currently in [this flix/flix folder]( https://github.com/flix/flix/tree/master/examples). And the ones ticked are the ones already on the home-page of the website. The rest are missing.

**Comment by magnus-madsen** [comment]
I think we should add all of them except `using-get-opt.flix` and `the-ast-typing-problem-with-polymorphic-records.flix`.

Will you do that? One challenge is to add them in a sensible order. On flix.dev we don't use an alphabetical order, but more an order of "easy relevant for everyone" to "difficult and only relevant for some".

**Comment by ninaandrup** [comment]
Yes, I notices the odd ordering. I will give it a try, and then we can always discuss the ordering

**Comment by magnus-madsen** [comment]
Sounds good. Possibly the examples should just go near the end.
